export const LOGIN = 'LOGIN'
export const REGISTER= 'REGISTER'
export const TOKEN = 'TOKEN'
export const USERINFO = 'USERINFO'
export const MAPINFO='MAPINFO'
export const UGVINFO='UGVINFO'
export const LOGINSTATUS = 'LOGINSTATUS'
export const REGISTERSTATUS= 'REGISTERSTATUS'
